CREATE DATABASE credit_card_project;
USE credit_card_project;
CREATE TABLE application_record (
ID BIGINT,
CODE_GENDER VARCHAR(10),
FLAG_OWN_CAR VARCHAR(10),
FLAG_OWN_REALTY VARCHAR(10),
CNT_CHILDREN INT,
AMT_INCOME_TOTAL FLOAT,
NAME_INCOME_TYPE VARCHAR(100),
NAME_EDUCATION_TYPE VARCHAR(100),
NAME_FAMILY_STATUS VARCHAR(100),
NAME_HOUSING_TYPE VARCHAR(100),
DAYS_BIRTH INT,
DAYS_EMPLOYED INT,
FLAG_MOBIL INT,
FLAG_WORK_PHONE INT,
FLAG_PHONE INT,
FLAG_EMAIL INT,
OCCUPATION_TYPE VARCHAR(100),
CNT_FAM_MEMBERS FLOAT,
Age INT,
Age_Group VARCHAR(50),
Income_Category VARCHAR(50),
Experience_Years INT
);
USE CREDIT_CARD_PROJECT;
SELECT * FROM application_record;
DROP DATABASE credit_card_project;
SELECT COUNT(*) FROM application_record;

#TO CHECK THE DATA 
SELECT *FROM application_record LIMIT 10;
# DATA CLEANING 
SELECT * FROM application_record WHERE OCCUPATION_TYPE IS NULL;
UPDATE application_record
SET OCCUPATION_TYPE='Unknown'
WHERE OCCUPATION_TYPE IS NULL;
#GENDER DISTRIBUTION 
SELECT
CODE_GENDER,
COUNT(*) AS Total_Customers
FROM application_record
GROUP BY CODE_GENDER;

#INCOME TYPE DISTRIBUTION 
SELECT
NAME_INCOME_TYPE,
COUNT(*) AS Total_Customers
FROM application_record
GROUP BY NAME_INCOME_TYPE;

#EDUCATION DISTRIBUTION 
SELECT
NAME_EDUCATION_TYPE,
COUNT(*) AS Total_Customers
FROM application_record
GROUP BY NAME_EDUCATION_TYPE;

#FAMILY STATUS DISTRIBUTION 
SELECT
NAME_FAMILY_STATUS,
COUNT(*) AS Total_Customers
FROM application_record
GROUP BY NAME_FAMILY_STATUS;

#HOUSING TYPE DISTRIBUTION 
SELECT
NAME_HOUSING_TYPE,
COUNT(*) AS Total_Customers
FROM application_record
GROUP BY NAME_HOUSING_TYPE;

#CREATE AGE GROUP 
ALTER TABLE application_record
ADD COLUMN Age_Group VARCHAR(20);
UPDATE application_record
SET Age_Group =
CASE
WHEN ABS(DAYS_BIRTH)/365 < 30 THEN 'Young'
WHEN ABS(DAYS_BIRTH)/365 BETWEEN 30 AND 50 THEN 'Mid Age'
ELSE 'Senior'
END;

#AGE GROUP DISTRIBUTION 
SELECT
Age_Group,
COUNT(*) AS Total_Customers
FROM application_record
GROUP BY Age_Group;

#CREATE INCOME CATEGORY 
ALTER TABLE application_record
ADD COLUMN Income_Category VARCHAR(20);

UPDATE application_record
SET Income_Category =
CASE
WHEN AMT_INCOME_TOTAL < 100000 THEN 'Low Income'
WHEN AMT_INCOME_TOTAL BETWEEN 100000 AND 300000 THEN 'Medium Income'
ELSE 'High Income'
END;

#INCOME CATEGORY DISTRIBUTION 
SELECT
Income_Category,
COUNT(*) AS Customers
FROM application_record
GROUP BY Income_Category;

#TOP CUSTOMER SEGMENT 
SELECT
Age_Group,
Income_Category,
COUNT(*) AS Customers
FROM application_record
GROUP BY Age_Group, Income_Category
ORDER BY Customers DESC;

# AVERAGE INCOME BY GENDER 
SELECT
CODE_GENDER,
AVG(AMT_INCOME_TOTAL) AS Avg_Income
FROM application_record
GROUP BY CODE_GENDER;

#AVERAGE INCOME BY EDUCTION 
SELECT
NAME_EDUCATION_TYPE,
AVG(AMT_INCOME_TOTAL) AS Avg_Income
FROM application_record
GROUP BY NAME_EDUCATION_TYPE
ORDER BY Avg_Income DESC;

#TOP OCCUPATION 
SELECT
OCCUPATION_TYPE,
COUNT(*) AS Employees
FROM application_record
GROUP BY OCCUPATION_TYPE
ORDER BY Employees DESC;
